name: langchain_gigachat
description: LangChain.dart unofficial integration module for SBER AI (GigaChat, GigaChat Pro) 
version: 0.1.2
repository: https://github.com/pwrshi/langchain_gigachat_dart

topics:
  - ai
  - nlp
  - llms
  - langchain
  - gigachat
  - sber

environment:
  sdk: "^3.3.0"

dev_dependencies:
  test: ^1.25.2
  very_good_analysis: ">=5.1.0 <7.0.0"
dependencies:
  collection: '>=1.17.0 <1.19.0'
  gigachat_dart: ^0.1.2
  http: ^1.2.1
  langchain_core: ^0.3.1
