name: langchain_gigachat
description: Wrapper for langchain_core and gigachat_dart
version: 0.1.0
publish_to: none

topics:
  - ai
  - nlp
  - llms
  - langchain
  - gigachat

environment:
  sdk: "^3.3.0"

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
dependencies:
  collection: '>=1.17.0 <1.19.0'
  freezed_annotation: ^2.4.1
  gigachat_dart: ^0.1.1
  http: ^1.2.1
  langchain_core: ^0.3.1
